const generateAnalysis = async (title, description) => {
    // Simulated delay to mimic processing
    await new Promise(resolve => setTimeout(resolve, 500));

    const keywords = (title + ' ' + description).toLowerCase();

    let strategic = "The regional power balance remains under careful observation. Strategic posture among primary state actors suggests a period of realignment, as nations reassess their long-term defense commitments and bilateral security arrangements. Intelligence indicators point towards a cautious approach to direct confrontation, with priority given to diplomatic signaling through formal and informal channels. Analysts emphasize that the current equilibrium is fragile, necessitating constant surveillance of satellite imagery and diplomatic backchannels.";
    let economic = "Market participants are analyzing the long-term implications for regional trade architecture. While immediate volatility is limited, the potential for policy-driven shifts in supply chain routes and foreign direct investment remains a significant variable. Analysts highlight the importance of monitoring central bank responses and trade ministry statements for signs of upcoming regulatory adjustments. Commodity markets, particularly in rare earths and transition minerals, are showing early signs of tactical positioning by major economic blocs.";
    let reaction = "The international community is responding with measured diplomatic engagement. Regional organizations are calling for multilateral discussions to address the underlying structural issues, while major powers are providing varying levels of support depending on their strategic interests. Expect a series of high-level summits to follow as the situation evolves. Humanitarian observers are flagging potential areas of concern, urging for transparency in state-level negotiations to ensure broader regional stability.";

    if (keywords.includes('war') || keywords.includes('military') || keywords.includes('attack') || keywords.includes('conflict') || keywords.includes('explosion') || keywords.includes('strike')) {
        strategic = "High risk of kinetic escalation and regional spillover. Defense ministries are activating rapid response protocols and satellite reconnaissance is monitoring troop movements in real-time. The activation of mutual defense clauses among allies is currently under discussion, indicating a significant shift from localized friction to a potential regional systemic crisis. Tactical deployment of advanced electronic warfare assets has been noted, suggesting a hardening of military postures across all theaters of operation.";
        economic = "Substantial disruption of critical supply chains, particularly in energy and semiconductor sectors, is anticipated. Global market indices are pricing in high-risk premiums as maritime shipping routes face potential blockades or increased insurance costs. Long-term capital flight from the affected region is a growing concern for international financial institutions. Energy prices are expected to remain volatile as strategic reserves are tapped to mitigate immediate supply shocks.";
        reaction = "Unprecedented condemnation from global security bodies. The UN Security Council is likely to convene for an emergency session, and a coordinated sanctions package from major economic blocs is being drafted. Humanitarian organizations are mobilizing resources in anticipation of large-scale population displacement. Non-aligned nations are being pressured to clarify their positions, complicating multi-vector diplomatic efforts to secure a ceasefire.";
    } else if (keywords.includes('trade') || keywords.includes('economy') || keywords.includes('deal') || keywords.includes('sanction') || keywords.includes('tariff') || keywords.includes('investment')) {
        strategic = "Economic statecraft is being utilized as a primary tool for geopolitical leverage. This development reshapes the competitive landscape by favoring specific trade blocs and creating new dependencies. Nations not directly involved are re-evaluating their economic neutrality and considering shifts in their strategic currency reserves. The weaponization of trade routes and critical infrastructure is now a central pillar of the broader strategic competition.";
        economic = "Direct impact on bilateral trade volumes and cross-border investment flows. The imposition of new regulatory hurdles or financial restrictions is expected to increase transaction costs and lead to market fragmentation. Emerging markets are particularly vulnerable to the resulting shifts in commodity prices and currency valuations. Multinational corporations are diversifying their operations to hedge against increasing geopolitical risk, leading to a trend of 'friend-shoring' in key industries.";
        reaction = "Mixed reactions from global trade organizations, with some calling for a return to rules-based international trade. Affected businesses are lobbying for exemptions or government support, while competing industries in other regions prepare to capitalize on the shifting market dynamics. Diplomatic notes have been exchanged highlighting the potential for retaliatory measures, raising fears of a broader 'tit-for-tat' economic escalation.";
    } else if (keywords.includes('election') || keywords.includes('vote') || keywords.includes('summit') || keywords.includes('coup') || keywords.includes('uprising') || keywords.includes('protest')) {
        strategic = "A potential transformative shift in national governance and foreign policy orientation. The outcome signifies a critical junction for regional stability, with implications for existing defense treaties and intelligence-sharing agreements. State actors are monitoring for signs of internal instability or external interference in the political transition. The preservation of democratic norms versus the rise of transactional authoritarianism is a key systemic theme being observed by international policy centers.";
        economic = "Heightened investment uncertainty as markets await clarification on future fiscal and monetary policies. Rating agencies are placed on high alert for sovereign credit adjustments, and multinational corporations are pausing major infrastructure projects pending signs of political continuity or stable new leadership. Speculative capital is moving into safe-haven assets, reflecting a broader 'wait-and-see' approach by global investors.";
        reaction = "A broad spectrum of international responses, ranging from cautious optimism to calls for the restoration of constitutional order. Neighbors are reinforcing border security to manage potential spillover effects, while global powers seek to establish early rapport with the emerging political leadership. Social media monitoring suggests a highly polarized public discourse, with coordinated disinformation campaigns attempting to influence both domestic and international perceptions.";
    }

    return {
        summary: `Comprehensive Strategic Intelligence Briefing: This significant development in ${keywords.includes('asia') ? 'Asian' : keywords.includes('europe') ? 'European' : keywords.includes('middle east') ? 'Middle Eastern' : 'Global'} geopolitics marks a critical inflection point for regional and international security architecture. Analysts at the center of geopolitical strategy suggest that the convergence of ${keywords.includes('military') ? 'advanced security imperatives and tactical re-alignment' : 'complex economic interdependencies and systemic competition'} will dictate the trajectory of diplomatic engagement for the foreseeable future. The situation is characterized by a high degree of fluid dynamics, where small shifts in state-level posture can have outsized continental effects. We advise stakeholders to maintain high-readiness posture and closely monitor state-level communications, border activity, and cyber-theater signatures to prevent miscalculation and ensure strategic resilience. The potential for 'black swan' events remains elevated during this period of transition. Further assessments will follow as more intelligence becomes available through our specialized regional monitoring nodes.`,
        strategicImpact: strategic,
        economicImpact: economic,
        globalReaction: reaction
    };
};

export default generateAnalysis;
