import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const countries = [
    { name: 'Afghanistan', flag: '🇦🇫', region: 'Asia', capital: 'Kabul' },
    { name: 'Albania', flag: '🇦🇱', region: 'Europe', capital: 'Tirana' },
    { name: 'Algeria', flag: '🇩🇿', region: 'Africa', capital: 'Algiers' },
    { name: 'Andorra', flag: '🇦🇩', region: 'Europe', capital: 'Andorra la Vella' },
    { name: 'Angola', flag: '🇦🇴', region: 'Africa', capital: 'Luanda' },
    { name: 'Antigua and Barbuda', flag: '🇦🇬', region: 'Americas', capital: "Saint John's" },
    { name: 'Argentina', flag: '🇦🇷', region: 'Americas', capital: 'Buenos Aires' },
    { name: 'Armenia', flag: '🇦🇲', region: 'Asia', capital: 'Yerevan' },
    { name: 'Australia', flag: '🇦🇺', region: 'Oceania', capital: 'Canberra' },
    { name: 'Austria', flag: '🇦🇹', region: 'Europe', capital: 'Vienna' },
    { name: 'Azerbaijan', flag: '🇦🇿', region: 'Asia', capital: 'Baku' },
    { name: 'Bahamas', flag: '🇧🇸', region: 'Americas', capital: 'Nassau' },
    { name: 'Bahrain', flag: '🇧🇭', region: 'Asia', capital: 'Manama' },
    { name: 'Bangladesh', flag: '🇧🇩', region: 'Asia', capital: 'Dhaka' },
    { name: 'Barbados', flag: '🇧🇧', region: 'Americas', capital: 'Bridgetown' },
    { name: 'Belarus', flag: '🇧🇾', region: 'Europe', capital: 'Minsk' },
    { name: 'Belgium', flag: '🇧🇪', region: 'Europe', capital: 'Brussels' },
    { name: 'Belize', flag: '🇧🇿', region: 'Americas', capital: 'Belmopan' },
    { name: 'Benin', flag: '🇧🇯', region: 'Africa', capital: 'Porto-Novo' },
    { name: 'Bhutan', flag: '🇧🇹', region: 'Asia', capital: 'Thimphu' },
    { name: 'Bolivia', flag: '🇧🇴', region: 'Americas', capital: 'Sucre' },
    { name: 'Bosnia and Herzegovina', flag: '🇧🇦', region: 'Europe', capital: 'Sarajevo' },
    { name: 'Botswana', flag: '🇧🇼', region: 'Africa', capital: 'Gaborone' },
    { name: 'Brazil', flag: '🇧🇷', region: 'Americas', capital: 'Brasilia' },
    { name: 'Brunei', flag: '🇧🇳', region: 'Asia', capital: 'Bandar Seri Begawan' },
    { name: 'Bulgaria', flag: '🇧🇬', region: 'Europe', capital: 'Sofia' },
    { name: 'Burkina Faso', flag: '🇧🇫', region: 'Africa', capital: 'Ouagadougou' },
    { name: 'Burundi', flag: '🇧🇮', region: 'Africa', capital: 'Gitega' },
    { name: 'Cabo Verde', flag: '🇨🇻', region: 'Africa', capital: 'Praia' },
    { name: 'Cambodia', flag: '🇰🇭', region: 'Asia', capital: 'Phnom Penh' },
    { name: 'Cameroon', flag: '🇨🇲', region: 'Africa', capital: 'Yaounde' },
    { name: 'Canada', flag: '🇨🇦', region: 'Americas', capital: 'Ottawa' },
    { name: 'Central African Republic', flag: '🇨🇫', region: 'Africa', capital: 'Bangui' },
    { name: 'Chad', flag: '🇹🇩', region: 'Africa', capital: "N'Djamena" },
    { name: 'Chile', flag: '🇨🇱', region: 'Americas', capital: 'Santiago' },
    { name: 'China', flag: '🇨🇳', region: 'Asia', capital: 'Beijing' },
    { name: 'Colombia', flag: '🇨🇴', region: 'Americas', capital: 'Bogota' },
    { name: 'Comoros', flag: '🇰🇲', region: 'Africa', capital: 'Moroni' },
    { name: 'Congo (Congo-Brazzaville)', flag: '🇨🇬', region: 'Africa', capital: 'Brazzaville' },
    { name: 'Congo (Democratic Republic of the)', flag: '🇨🇩', region: 'Africa', capital: 'Kinshasa' },
    { name: 'Costa Rica', flag: '🇨🇷', region: 'Americas', capital: 'San Jose' },
    { name: "Cote d'Ivoire", flag: '🇨🇮', region: 'Africa', capital: 'Yamoussoukro' },
    { name: 'Croatia', flag: '🇭🇷', region: 'Europe', capital: 'Zagreb' },
    { name: 'Cuba', flag: '🇨🇺', region: 'Americas', capital: 'Havana' },
    { name: 'Cyprus', flag: '🇨🇾', region: 'Europe', capital: 'Nicosia' },
    { name: 'Czechia (Czech Republic)', flag: '🇨🇿', region: 'Europe', capital: 'Prague' },
    { name: 'Denmark', flag: '🇩🇰', region: 'Europe', capital: 'Copenhagen' },
    { name: 'Djibouti', flag: '🇩🇯', region: 'Africa', capital: 'Djibouti' },
    { name: 'Dominica', flag: '🇩🇲', region: 'Americas', capital: 'Roseau' },
    { name: 'Dominican Republic', flag: '🇩🇴', region: 'Americas', capital: 'Santo Domingo' },
    { name: 'Ecuador', flag: '🇪🇨', region: 'Americas', capital: 'Quito' },
    { name: 'Egypt', flag: '🇪🇬', region: 'Africa', capital: 'Cairo' },
    { name: 'El Salvador', flag: '🇸🇻', region: 'Americas', capital: 'San Salvador' },
    { name: 'Equatorial Guinea', flag: '🇬🇶', region: 'Africa', capital: 'Malabo' },
    { name: 'Eritrea', flag: '🇪🇷', region: 'Africa', capital: 'Asmara' },
    { name: 'Estonia', flag: '🇪🇪', region: 'Europe', capital: 'Tallinn' },
    { name: 'Eswatini', flag: '🇸🇿', region: 'Africa', capital: 'Mbabane' },
    { name: 'Ethiopia', flag: '🇪🇹', region: 'Africa', capital: 'Addis Ababa' },
    { name: 'Fiji', flag: '🇫🇯', region: 'Oceania', capital: 'Suva' },
    { name: 'Finland', flag: '🇫🇮', region: 'Europe', capital: 'Helsinki' },
    { name: 'France', flag: '🇫🇷', region: 'Europe', capital: 'Paris' },
    { name: 'Gabon', flag: '🇬🇦', region: 'Africa', capital: 'Libreville' },
    { name: 'Gambia', flag: '🇬🇲', region: 'Africa', capital: 'Banjul' },
    { name: 'Georgia', flag: '🇬🇪', region: 'Asia', capital: 'Tbilisi' },
    { name: 'Germany', flag: '🇩🇪', region: 'Europe', capital: 'Berlin' },
    { name: 'Ghana', flag: '🇬🇭', region: 'Africa', capital: 'Accra' },
    { name: 'Greece', flag: '🇬🇷', region: 'Europe', capital: 'Athens' },
    { name: 'Grenada', flag: '🇬🇩', region: 'Americas', capital: "Saint George's" },
    { name: 'Guatemala', flag: '🇬🇹', region: 'Americas', capital: 'Guatemala City' },
    { name: 'Guinea', flag: '🇬🇳', region: 'Africa', capital: 'Conakry' },
    { name: 'Guinea-Bissau', flag: '🇬🇼', region: 'Africa', capital: 'Bissau' },
    { name: 'Guyana', flag: '🇬🇾', region: 'Americas', capital: 'Georgetown' },
    { name: 'Haiti', flag: '🇭🇹', region: 'Americas', capital: 'Port-au-Prince' },
    { name: 'Holy See', flag: '🇻🇦', region: 'Europe', capital: 'Vatican City' },
    { name: 'Honduras', flag: '🇭🇳', region: 'Americas', capital: 'Tegucigalpa' },
    { name: 'Hungary', flag: '🇭🇺', region: 'Europe', capital: 'Budapest' },
    { name: 'Iceland', flag: '🇮🇸', region: 'Europe', capital: 'Reykjavik' },
    { name: 'India', flag: '🇮🇳', region: 'Asia', capital: 'New Delhi' },
    { name: 'Indonesia', flag: '🇮🇩', region: 'Asia', capital: 'Jakarta' },
    { name: 'Iran', flag: '🇮🇷', region: 'Asia', capital: 'Tehran' },
    { name: 'Iraq', flag: '🇮🇶', region: 'Asia', capital: 'Baghdad' },
    { name: 'Ireland', flag: '🇮🇪', region: 'Europe', capital: 'Dublin' },
    { name: 'Israel', flag: '🇮🇱', region: 'Asia', capital: 'Jerusalem' },
    { name: 'Italy', flag: '🇮🇹', region: 'Europe', capital: 'Rome' },
    { name: 'Jamaica', flag: '🇯🇲', region: 'Americas', capital: 'Kingston' },
    { name: 'Japan', flag: '🇯🇵', region: 'Asia', capital: 'Tokyo' },
    { name: 'Jordan', flag: '🇯🇴', region: 'Asia', capital: 'Amman' },
    { name: 'Kazakhstan', flag: '🇰🇿', region: 'Asia', capital: 'Nur-Sultan' },
    { name: 'Kenya', flag: '🇰🇪', region: 'Africa', capital: 'Nairobi' },
    { name: 'Kiribati', flag: '🇰🇮', region: 'Oceania', capital: 'South Tarawa' },
    { name: 'Kuwait', flag: '🇰🇼', region: 'Asia', capital: 'Kuwait City' },
    { name: 'Kyrgyzstan', flag: '🇰🇬', region: 'Asia', capital: 'Bishkek' },
    { name: 'Laos', flag: '🇱🇦', region: 'Asia', capital: 'Vientiane' },
    { name: 'Latvia', flag: '🇱🇻', region: 'Europe', capital: 'Riga' },
    { name: 'Lebanon', flag: '🇱🇧', region: 'Asia', capital: 'Beirut' },
    { name: 'Lesotho', flag: '🇱🇸', region: 'Africa', capital: 'Maseru' },
    { name: 'Liberia', flag: '🇱🇷', region: 'Africa', capital: 'Monrovia' },
    { name: 'Libya', flag: '🇱🇾', region: 'Africa', capital: 'Tripoli' },
    { name: 'Liechtenstein', flag: '🇱🇮', region: 'Europe', capital: 'Vaduz' },
    { name: 'Lithuania', flag: '🇱🇹', region: 'Europe', capital: 'Vilnius' },
    { name: 'Luxembourg', flag: '🇱🇺', region: 'Europe', capital: 'Luxembourg' },
    { name: 'Madagascar', flag: '🇲🇬', region: 'Africa', capital: 'Antananarivo' },
    { name: 'Malawi', flag: '🇲🇼', region: 'Africa', capital: 'Lilongwe' },
    { name: 'Malaysia', flag: '🇲🇾', region: 'Asia', capital: 'Kuala Lumpur' },
    { name: 'Maldives', flag: '🇲🇻', region: 'Asia', capital: 'Male' },
    { name: 'Mali', flag: '🇲🇱', region: 'Africa', capital: 'Bamako' },
    { name: 'Malta', flag: '🇲🇹', region: 'Europe', capital: 'Valletta' },
    { name: 'Marshall Islands', flag: '🇲🇭', region: 'Oceania', capital: 'Majuro' },
    { name: 'Mauritania', flag: '🇲🇷', region: 'Africa', capital: 'Nouakchott' },
    { name: 'Mauritius', flag: '🇲🇺', region: 'Africa', capital: 'Port Louis' },
    { name: 'Mexico', flag: '🇲🇽', region: 'Americas', capital: 'Mexico City' },
    { name: 'Micronesia', flag: '🇫🇲', region: 'Oceania', capital: 'Palikir' },
    { name: 'Moldova', flag: '🇲🇩', region: 'Europe', capital: 'Chisinau' },
    { name: 'Monaco', flag: '🇲🇨', region: 'Europe', capital: 'Monaco' },
    { name: 'Mongolia', flag: '🇲🇳', region: 'Asia', capital: 'Ulaanbaatar' },
    { name: 'Montenegro', flag: '🇲🇪', region: 'Europe', capital: 'Podgorica' },
    { name: 'Morocco', flag: '🇲🇦', region: 'Africa', capital: 'Rabat' },
    { name: 'Mozambique', flag: '🇲🇿', region: 'Africa', capital: 'Maputo' },
    { name: 'Myanmar', flag: '🇲🇲', region: 'Asia', capital: 'Naypyidaw' },
    { name: 'Namibia', flag: '🇳🇦', region: 'Africa', capital: 'Windhoek' },
    { name: 'Nauru', flag: '🇳🇷', region: 'Oceania', capital: 'Yaren District' },
    { name: 'Nepal', flag: '🇳🇵', region: 'Asia', capital: 'Kathmandu' },
    { name: 'Netherlands', flag: '🇳🇱', region: 'Europe', capital: 'Amsterdam' },
    { name: 'New Zealand', flag: '🇳🇿', region: 'Oceania', capital: 'Wellington' },
    { name: 'Nicaragua', flag: '🇳🇮', region: 'Americas', capital: 'Managua' },
    { name: 'Niger', flag: '🇳🇪', region: 'Africa', capital: 'Niamey' },
    { name: 'Nigeria', flag: '🇳🇬', region: 'Africa', capital: 'Abuja' },
    { name: 'North Korea', flag: '🇰🇵', region: 'Asia', capital: 'Pyongyang' },
    { name: 'North Macedonia', flag: '🇲🇰', region: 'Europe', capital: 'Skopje' },
    { name: 'Norway', flag: '🇳🇴', region: 'Europe', capital: 'Oslo' },
    { name: 'Oman', flag: '🇴🇲', region: 'Asia', capital: 'Muscat' },
    { name: 'Pakistan', flag: '🇵🇰', region: 'Asia', capital: 'Islamabad' },
    { name: 'Palau', flag: '🇵🇼', region: 'Oceania', capital: 'Ngerulmud' },
    { name: 'Palestine State', flag: '🇵🇸', region: 'Asia', capital: 'Jerusalem' },
    { name: 'Panama', flag: '🇵🇦', region: 'Americas', capital: 'Panama City' },
    { name: 'Papua New Guinea', flag: '🇵🇬', region: 'Oceania', capital: 'Port Moresby' },
    { name: 'Paraguay', flag: '🇵🇾', region: 'Americas', capital: 'Asuncion' },
    { name: 'Peru', flag: '🇵🇪', region: 'Americas', capital: 'Lima' },
    { name: 'Philippines', flag: '🇵🇭', region: 'Asia', capital: 'Manila' },
    { name: 'Poland', flag: '🇵🇱', region: 'Europe', capital: 'Warsaw' },
    { name: 'Portugal', flag: '🇵🇹', region: 'Europe', capital: 'Lisbon' },
    { name: 'Qatar', flag: '🇶🇦', region: 'Asia', capital: 'Doha' },
    { name: 'Romania', flag: '🇷🇴', region: 'Europe', capital: 'Bucharest' },
    { name: 'Russia', flag: '🇷🇺', region: 'Europe', capital: 'Moscow' },
    { name: 'Rwanda', flag: '🇷🇼', region: 'Africa', capital: 'Kigali' },
    { name: 'Saint Kitts and Nevis', flag: '🇰🇳', region: 'Americas', capital: 'Basseterre' },
    { name: 'Saint Lucia', flag: '🇱🇨', region: 'Americas', capital: 'Castries' },
    { name: 'Saint Vincent and the Grenadines', flag: '🇻🇨', region: 'Americas', capital: 'Kingstown' },
    { name: 'Samoa', flag: '🇼🇸', region: 'Oceania', capital: 'Apia' },
    { name: 'San Marino', flag: '🇸🇲', region: 'Europe', capital: 'San Marino' },
    { name: 'Sao Tome and Principe', flag: '🇸🇹', region: 'Africa', capital: 'Sao Tome' },
    { name: 'Saudi Arabia', flag: '🇸🇦', region: 'Asia', capital: 'Riyadh' },
    { name: 'Senegal', flag: '🇸🇳', region: 'Africa', capital: 'Dakar' },
    { name: 'Serbia', flag: '🇷🇸', region: 'Europe', capital: 'Belgrade' },
    { name: 'Seychelles', flag: '🇸🇨', region: 'Africa', capital: 'Victoria' },
    { name: 'Sierra Leone', flag: '🇸🇱', region: 'Africa', capital: 'Freetown' },
    { name: 'Singapore', flag: '🇸🇬', region: 'Asia', capital: 'Singapore' },
    { name: 'Slovakia', flag: '🇸🇰', region: 'Europe', capital: 'Bratislava' },
    { name: 'Slovenia', flag: '🇸🇮', region: 'Europe', capital: 'Ljubljana' },
    { name: 'Solomon Islands', flag: '🇸🇧', region: 'Oceania', capital: 'Honiara' },
    { name: 'Somalia', flag: '🇸🇴', region: 'Africa', capital: 'Mogadishu' },
    { name: 'South Africa', flag: '🇿🇦', region: 'Africa', capital: 'Pretoria' },
    { name: 'South Korea', flag: '🇰🇷', region: 'Asia', capital: 'Seoul' },
    { name: 'South Sudan', flag: '🇸🇸', region: 'Africa', capital: 'Juba' },
    { name: 'Spain', flag: '🇪🇸', region: 'Europe', capital: 'Madrid' },
    { name: 'Sri Lanka', flag: '🇱🇰', region: 'Asia', capital: 'Sri Jayawardenepura Kotte' },
    { name: 'Sudan', flag: '🇸🇩', region: 'Africa', capital: 'Khartoum' },
    { name: 'Suriname', flag: '🇸🇷', region: 'Americas', capital: 'Paramaribo' },
    { name: 'Sweden', flag: '🇸🇪', region: 'Europe', capital: 'Stockholm' },
    { name: 'Switzerland', flag: '🇨🇭', region: 'Europe', capital: 'Bern' },
    { name: 'Syria', flag: '🇸🇾', region: 'Asia', capital: 'Damascus' },
    { name: 'Tajikistan', flag: '🇹🇯', region: 'Asia', capital: 'Dushanbe' },
    { name: 'Tanzania', flag: '🇹🇿', region: 'Africa', capital: 'Dodoma' },
    { name: 'Thailand', flag: '🇹🇭', region: 'Asia', capital: 'Bangkok' },
    { name: 'Timor-Leste', flag: '🇹🇱', region: 'Asia', capital: 'Dili' },
    { name: 'Togo', flag: '🇹🇬', region: 'Africa', capital: 'Lome' },
    { name: 'Tonga', flag: '🇹🇴', region: 'Oceania', capital: "Nuku'alofa" },
    { name: 'Trinidad and Tobago', flag: '🇹🇹', region: 'Americas', capital: 'Port of Spain' },
    { name: 'Tunisia', flag: '🇹🇳', region: 'Africa', capital: 'Tunis' },
    { name: 'Turkey', flag: '🇹🇷', region: 'Asia', capital: 'Ankara' },
    { name: 'Turkmenistan', flag: '🇹🇲', region: 'Asia', capital: 'Ashgabat' },
    { name: 'Tuvalu', flag: '🇹🇻', region: 'Oceania', capital: 'Funafuti' },
    { name: 'Uganda', flag: '🇺🇬', region: 'Africa', capital: 'Kampala' },
    { name: 'Ukraine', flag: '🇺🇦', region: 'Europe', capital: 'Kyiv' },
    { name: 'United Arab Emirates', flag: '🇦🇪', region: 'Asia', capital: 'Abu Dhabi' },
    { name: 'United Kingdom', flag: '🇬🇧', region: 'Europe', capital: 'London' },
    { name: 'United States', flag: '🇺🇸', region: 'Americas', capital: 'Washington, D.C.' },
    { name: 'Uruguay', flag: '🇺🇾', region: 'Americas', capital: 'Montevideo' },
    { name: 'Uzbekistan', flag: '🇺🇿', region: 'Asia', capital: 'Tashkent' },
    { name: 'Vanuatu', flag: '🇻🇺', region: 'Oceania', capital: 'Port Vila' },
    { name: 'Venezuela', flag: '🇻🇪', region: 'Americas', capital: 'Caracas' },
    { name: 'Vietnam', flag: '🇻🇳', region: 'Asia', capital: 'Hanoi' },
    { name: 'Yemen', flag: '🇾🇪', region: 'Asia', capital: "Sana'a" },
    { name: 'Zambia', flag: '🇿🇲', region: 'Africa', capital: 'Lusaka' },
    { name: 'Zimbabwe', flag: '🇿🇼', region: 'Africa', capital: 'Harare' }
];

const statsPath = path.join(__dirname, '..', 'data', 'countryStats.json');

try {
    let existingStats = {};
    if (fs.existsSync(statsPath)) {
        existingStats = JSON.parse(fs.readFileSync(statsPath, 'utf8'));
    }

    const newStats = {};
    countries.forEach(c => {
        // Basic entry
        newStats[c.name] = { ...(existingStats[c.name] || {}), ...c };

        // Add explicit alias entries to ensure they appear in search results directly
        if (c.name === 'United States') {
            newStats['USA'] = { ...newStats[c.name], name: 'USA' };
            newStats['US'] = { ...newStats[c.name], name: 'US' };
        }
        if (c.name === 'United Kingdom') {
            newStats['UK'] = { ...newStats[c.name], name: 'UK' };
        }
        if (c.name === 'United Arab Emirates') {
            newStats['UAE'] = { ...newStats[c.name], name: 'UAE' };
        }
        if (c.name === 'Russian Federation') {
            newStats['Russia'] = { ...newStats[c.name], name: 'Russia' };
        }
    });

    fs.writeFileSync(statsPath, JSON.stringify(newStats, null, 4));
    console.log(`Updated countryStats.json with ${Object.keys(newStats).length} entries (including aliases).`);
} catch (err) {
    console.error('Error:', err);
    process.exit(1);
}
